/**
 * The icons worth offering before anyone types anything: what a diagram reaches for most
 * often, grouped by what they stand for rather than listed alphabetically.
 *
 * It is a starting point, not a limit — the picker searches the whole set, and a document
 * may name any icon in it. One list serves two readers: the picker shows it before a
 * search narrows things down, and the generated JSON schema names the same icons so an AI
 * has somewhere to start. A test pins every name to an icon that exists.
 */
export const COMMON_ICON_GROUPS = [
	{
		label: "people",
		names: ["user", "users", "user-round", "circle-user", "contact"],
	},
	{
		label: "devices",
		names: [
			"monitor",
			"smartphone",
			"tablet",
			"laptop",
			"server",
			"hard-drive",
			"cpu",
			"printer",
			"webcam",
		],
	},
	{
		label: "infrastructure",
		names: [
			"cloud",
			"cloud-upload",
			"cloud-download",
			"database",
			"network",
			"router",
			"wifi",
			"globe",
			"radio-tower",
		],
	},
	{
		label: "files",
		names: [
			"file",
			"file-text",
			"files",
			"folder",
			"folder-open",
			"archive",
			"save",
			"book",
			"clipboard",
		],
	},
	{
		label: "messaging",
		names: [
			"mail",
			"message-square",
			"message-circle",
			"send",
			"bell",
			"phone",
			"rss",
			"share-2",
			"link",
			"at-sign",
		],
	},
	{
		label: "security",
		names: [
			"lock",
			"lock-open",
			"shield",
			"shield-check",
			"key",
			"key-round",
			"fingerprint-pattern",
			"eye",
			"eye-off",
			"scan-face",
		],
	},
	{
		label: "status",
		names: [
			"check",
			"circle-check",
			"x",
			"circle-x",
			"triangle-alert",
			"info",
			"circle-question-mark",
			"octagon-alert",
			"ban",
			"loader",
			"hourglass",
			"clock",
			"timer",
		],
	},
	{
		label: "actions",
		names: [
			"plus",
			"minus",
			"pencil",
			"square-pen",
			"trash-2",
			"copy",
			"clipboard-copy",
			"download",
			"upload",
			"refresh-cw",
			"rotate-ccw",
			"play",
			"pause",
			"settings",
			"sliders-horizontal",
			"funnel",
			"search",
			"zoom-in",
			"external-link",
		],
	},
	{
		label: "flow",
		names: [
			"arrow-right",
			"arrow-left",
			"arrow-up",
			"arrow-down",
			"arrow-right-left",
			"chevron-right",
			"chevron-down",
			"corner-down-right",
			"git-branch",
			"git-merge",
			"workflow",
			"split",
			"merge",
		],
	},
	{
		label: "data and code",
		names: [
			"chart-line",
			"chart-bar",
			"chart-pie",
			"table",
			"list",
			"layers",
			"box",
			"package",
			"boxes",
			"binary",
			"braces",
			"code",
			"terminal",
			"bug",
		],
	},
	{
		label: "business",
		names: [
			"building",
			"building-2",
			"factory",
			"store",
			"shopping-cart",
			"credit-card",
			"banknote",
			"receipt",
			"briefcase",
			"calendar",
			"users-round",
		],
	},
	{
		label: "other",
		names: [
			"star",
			"heart",
			"flag",
			"bookmark",
			"tag",
			"map-pin",
			"lightbulb",
			"zap",
			"flame",
			"sparkles",
			"wrench",
			"hammer",
			"cog",
			"gauge",
			"activity",
			"target",
			"trending-up",
			"trending-down",
			"thumbs-up",
			"face-slightly-smiling",
			"alarm-clock",
			"rocket",
			"gift",
			"coffee",
			"leaf",
			"sun",
			"moon",
		],
	},
] as const satisfies readonly { label: string; names: readonly string[] }[];

/** Every name in {@link COMMON_ICON_GROUPS}, flattened in the same order. */
export const COMMON_ICON_NAMES: readonly string[] = COMMON_ICON_GROUPS.flatMap(
	(group) => group.names,
);
