export { calculateScrollDelta } from "./calculateScrollDelta";
export { detectEdgeProximity, type EdgeProximity } from "./detectEdgeProximity";
export { findGestureElement, type GestureToken } from "./findGestureElement";
export { getHoveredElements } from "./getHoveredElements";
export { getInputValue } from "./getInputValue";
export { getKindAndId } from "./getKindAndId";
export { getSvgPoint } from "./getSvgPoint";
export { isGestureOptedOut } from "./isGestureOptedOut";
export { shouldSkipPointerCapture } from "./shouldSkipPointerCapture";
export { shouldUseNativeWheel } from "./shouldUseNativeWheel";
