export { calculateScrollDelta } from "./calculateScrollDelta";
export { detectEdgeProximity, type EdgeProximity } from "./detectEdgeProximity";
export { findGestureElement, type GestureToken } from "./findGestureElement";
export { createGetHovered, getHoveredElements } from "./getHoveredElements";
export { getInputValue, readInputValue } from "./getInputValue";
export { getKindAndId } from "./getKindAndId";
export { getSvgPoint } from "./getSvgPoint";
export { isDoubleClick } from "./isDoubleClick";
export { isGestureOptedOut } from "./isGestureOptedOut";
export { isNativePointerTarget } from "./isNativePointerTarget";
export { shouldUseNativeWheel } from "./shouldUseNativeWheel";
