// Re-export shim for the stable headless API, which lives in its own package now
// (`@jiscribe/doc`). Every in-repo consumer has migrated to `@jiscribe/doc`; this
// entry stays for consumers outside the repo that still name `@jiscribe/canvas/doc`.
//
// The names are listed rather than star-exported: a `.ts` file in this package is
// CommonJS to tsx (no `"type": "module"`), and a star re-export of another CJS module
// leaves nothing for Node's named-export detection to find, so an ESM consumer — the
// ai-docs generator is the one in hand — gets an empty namespace. Add a name here when
// adding one to `@jiscribe/doc`, until every consumer has moved over and this file goes
// away.

export {
	FILL_STYLE_KEYS,
	STROKE_STYLE_KEYS,
	RADIUS_STYLE_KEYS,
	ARROW_STYLE_KEYS,
	TRANSFORM_STYLE_KEYS,
	isTextRows,
	isTextSlot,
	resolveTextSlotStyle,
	TEXT_BLOCK_STYLE_KEYS,
	TEXT_SLOT_STYLE_KEYS,
	isRichText,
	isTextRun,
	normalizeRichText,
	remapRichText,
	richTextToPlain,
	sliceRichText,
	styleRichTextRange,
	TEXT_INLINE_STYLE_KEYS,
	createCanvasParser,
	builtinObjectDocDefinitions,
	createDocOps,
	DocOperationError,
} from "@jiscribe/doc";
export type {
	CanvasDoc,
	ObjectDoc,
	ObjectType,
	ObjectFeatures,
	CreateObjectType,
	TextSlot,
	TextSlotContent,
	TextSlotStyle,
	InlineTextStyle,
	RichText,
	TextRun,
	ExtraStylePropertyDescriptor,
	StyleValueType,
	ObjectDocDefinition,
	ObjectTextSlotStyleDefaults,
	CanvasDocPlugin,
	ObjectDocValidateFn,
	SemanticDiagnostic,
	CanvasParser,
	CanvasParseResult,
	AddObjectEntry,
	AddObjectParams,
	AlignEdge,
	AnchorHandleId,
	ConnectParams,
	DeleteObjectsResult,
	DistributeAxis,
	DocOps,
	GetZOrderResult,
	EdgeAnchorHandle,
	EdgeAnchorSide,
	InlineTextStyleParams,
	ObjectFilter,
	ObjectSummary,
	ObjectTypeSummary,
	Point,
	Rect,
	RemoveObjectsFromGroupResult,
	ResizeObjectParams,
	SetInlineTextStyleEntry,
	SetPointsEntry,
	SetPositionEntry,
	SetPositionParams,
	SetRotationResult,
	SetStyleResult,
	SetTextEntry,
	StyleParams,
	UpdateConnectorEntry,
	UpdateConnectorParams,
	ZOrderPlacement,
} from "@jiscribe/doc";
