import { roundToDecimal } from "@workspace/geometry";
import type { Point } from "@workspace/geometry";

import { collectConnectorPoints } from "./calcConnectorBoundingBox";
import { PRECISION } from "../../constants/precision";
import type { ObjectState } from "../../states/objects/base/ObjectState";
import {
	isConnectorState,
	type ConnectorState,
} from "../../states/objects/connections/connector/ConnectorState";
import type { CanvasControllerState } from "../CanvasTypes";
import type { ICanvasRegistries } from "../registries/ICanvasRegistries";

const isSamePointList = (a: readonly Point[], b: readonly Point[]): boolean =>
	a.length === b.length &&
	a.every((point, index) => point.x === b[index].x && point.y === b[index].y);

/**
 * Aligns every shaped connector's stored vertices (`points`) to the path being drawn.
 *
 * Rendering adapts the stored vertices to the current endpoints every frame (alignVertexPath 参照)
 * without writing them back, so the stored list lags behind whenever a connected shape moves. This
 * settles the difference the other way: the drawn path's interior, rounded to
 * PRECISION.COORDINATE, becomes the stored vertices. The alignment is count-preserving and this
 * function deletes nothing — corners degenerated by moves stay until a drag's own cleanup takes
 * them (moveConnectorSegment 参照).
 *
 * Connectors with no vertices stay the engine's to route, unresolvable paths are left as they
 * are, and a connector whose stored list already matches is left untouched — re-running is free,
 * and object references only change where a value did.
 *
 * @param state - The controller state whose connectors are settled against its own objects
 * @param registries - Outline / anchor-region registries used to resolve the drawn endpoints
 * @returns The same state reference when nothing diverged; otherwise a state with the rewritten
 *   connectors swapped in
 */
export const reconcileConnectorVertices = (
	state: CanvasControllerState,
	registries: ICanvasRegistries,
): CanvasControllerState => {
	let reconciledObjects: Record<string, ObjectState> | null = null;

	for (const object of Object.values(state.objects)) {
		if (!isConnectorState(object) || object.points.length === 0) {
			continue;
		}
		const drawnPath = collectConnectorPoints(
			object,
			state.objects,
			registries.objectOutline,
			registries.objectAnchorRegion,
		);
		if (!drawnPath) {
			continue;
		}
		const alignedPoints = drawnPath.slice(1, -1).map((point) => ({
			x: roundToDecimal(point.x, PRECISION.COORDINATE),
			y: roundToDecimal(point.y, PRECISION.COORDINATE),
		}));
		if (isSamePointList(alignedPoints, object.points)) {
			continue;
		}
		if (!reconciledObjects) {
			reconciledObjects = { ...state.objects };
		}
		reconciledObjects[object.id] = {
			...object,
			points: alignedPoints,
		} as ConnectorState;
	}

	if (!reconciledObjects) {
		return state;
	}
	return { ...state, objects: reconciledObjects };
};

/**
 * reconcileConnectorVertices with the commit gate on top: runs only when this transition raised
 * `commitVersion` (the same test recordHistoryIfNeeded applies). Undo/redo restore snapshots
 * without raising it, and external sync bypasses this path entirely, so neither rewrites
 * `points` — the doc stays untouched outside the user's own committed edits.
 *
 * @param state - The transition's resulting state
 * @param previousState - The state the transition started from, carrying the previous commitVersion
 * @param registries - Outline / anchor-region registries used to resolve the drawn endpoints
 */
export const reconcileConnectorVerticesIfCommitted = (
	state: CanvasControllerState,
	previousState: CanvasControllerState,
	registries: ICanvasRegistries,
): CanvasControllerState => {
	const isCommitted =
		state.commitVersion > 0 &&
		state.commitVersion !== previousState.commitVersion;
	if (!isCommitted) {
		return state;
	}
	return reconcileConnectorVertices(state, registries);
};
